name: CI Barbearia Alura
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  job1:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: latest
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask 
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: '${{secrets.HEROKU_DEPLOY}}'
          heroku_app_name: devops-barbeariaalura
          heroku_email: fernandorberto@gmail.com
          procfile: 'web: gunicorn app:app'
